# Generated by Django 4.2 on 2023-07-13 20:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scrapbook",
            fields=[
                ("scrapbook_id", models.AutoField(primary_key=True, serialize=False)),
                ("scrapbook_name", models.CharField(max_length=255)),
                ("scrapbook_info", models.TextField()),
                ("content_num", models.IntegerField()),
            ],
            options={"db_table": "SCRAPBOOK",},
        ),
        migrations.CreateModel(
            name="VocaInfo",
            fields=[
                ("voca_id", models.AutoField(primary_key=True, serialize=False)),
                ("voca_name", models.CharField(max_length=255)),
                ("voca_info", models.TextField()),
                ("word_num", models.IntegerField(default=0)),
                ("sentence_num", models.IntegerField(default=0)),
            ],
            options={"db_table": "VOCAINFO",},
        ),
        migrations.CreateModel(
            name="VocaSentence",
            fields=[
                ("sentence_id", models.AutoField(primary_key=True, serialize=False)),
                ("sentence", models.TextField()),
                ("s_meaning", models.TextField()),
                (
                    "s_voca_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WMVoca.vocainfo",
                    ),
                ),
            ],
            options={"db_table": "VOCASENTENCE",},
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254)),

            ],
            options={"db_table": "UserInfo",},
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="VocaWord",
            fields=[
                ("word_id", models.AutoField(primary_key=True, serialize=False)),
                ("word", models.CharField(max_length=255)),
                ("w_meaning", models.TextField()),
                ("save_memory", models.BooleanField()),
                (
                    "w_sentence_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WMVoca.vocasentence",
                    ),
                ),
                (
                    "w_voca_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WMVoca.vocainfo",
                    ),
                ),
            ],
            options={"db_table": "VOCAWORD",},
        ),
        migrations.AddField(
            model_name="vocainfo",
            name="v_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ScrapbookContent",
            fields=[
                ("content_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("c_meaning", models.TextField()),
                (
                    "c_scrapbook_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="WMVoca.scrapbook",
                    ),
                ),
            ],
            options={"db_table": "SCRAPBOOKCONTENT",},
        ),
        migrations.AddField(
            model_name="scrapbook",
            name="sb_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
